### ISSUE TITLE
Replace lmp-gateway-image with lmp-base-console-image on supported hardware page

### ISSUE THREAD

**Issue by mike-scott** [foundriesio/docs#136]
Here:
https://docs.foundries.io/latest/reference-manual/linux/linux-targets.html?highlight=gateway

We refer to `lmp-gateway-image-*` files for flashing.
This is being changed to `lmp-base-console-image-*` with the release of v75.

**Comment by MatthewCroughan** [comment]
Grepping for this shows that there are other references remaining. If we simply replace these references, will it still make sense in their context?

For example, will we be able to `bitbake lmp-base-console-image` after running the `setup-environment` script, after cloning and `repo sync`ing this git repo? https://github.com/foundriesio/lmp-manifest. This is explained in `linux-building-rst`

And in `linux-layers.rst` we reference the gateway image again in order to explain where its recipe is defined in meta-lmp. We do not have a `lmp-base-console-image.bb` in the meta-lmp repo yet, will this eventually be the location of the new base console image recipe?

```
matthew@thinkpad ~/git/foundries/docs/source (improvements-01) $ grep -r 'lmp-gateway-image'
reference-manual/linux/linux-layers.rst:The ``lmp-gateway-image`` recipe can be found at
reference-manual/linux/linux-layers.rst:``recipes-samples/images/lmp-gateway-image.bb``. You can find the
reference-manual/linux/linux-building.rst:  bitbake lmp-gateway-image
reference-manual/linux/linux-building.rst:``lmp-gateway-image-raspberrypi3-64.wic.gz``.
```
